### ISSUE TITLE
Lab 06a: Enabling Continuous Integration with Azure Pipelines

### ISSUE THREAD

**Issue by PlantScope** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#181]
### Contact Details

DTAExecutionHost.exe failed with exit code 1  for 

### What happened?

Module.: https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/Instructions/Labs/AZ400_M06_Enabling_Continuous_Integration_with_Azure_Pipelines.md
Exercise : 01
Task: 01
Step: 10-16

Description of issue:
Error: The process 'C:\agent_work_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\Modules\DTAExecutionHost.exe' failed with exit code 1 Vstest failed with error. Check logs for failures. There might be failed tests.
Repro steps: 
1. Step 1 says "from window-2019 to vs2017-win2016", but the latter does not exist.
2. use "window-2019"
3. use step 16 to build it.

### Lab

Lab 06a Enabling Continuous Integration with Azure Pipelines

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Requestt by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by PlantScope** [comment]
P.S.: MS decommissioned the windows-2016 images.

**Comment by rob-foulkrod** [comment]
There are new commits to the PartsUnlimited repo that look to starting the process of being able to run on the windows-2019 agent. But these changes have resulted in several of the tests failing.
![Screenshot showing 8 out of 16 tests failing](https://user-images.githubusercontent.com/89028299/145256121-5e97d2d3-b801-4f34-94a2-88a721c092ae.png)

This failure seems to be caused by issues between .NET Framework 4.5.1 and Moq and Castle.Core.

Upgrading the Web App and the Unit test project to .NET Framework 4.6.1 seems to resolve the issues and the tests pass.

![Screenshot showing 14 of 16 tests passing (2 skipped)](https://user-images.githubusercontent.com/89028299/145256792-fdb54e4a-3471-491b-bcae-82e64780396c.png)

Obviously, this will have to be done in the DevOpsGenerator project and not something students can fix.

Temporary fixes include:
- disabling the Test Assemblies step prior to running
    
    ![image](https://user-images.githubusercontent.com/89028299/145257356-795be056-679a-4e0f-8258-bc05f74fba0b.png)

- or, Creating a branch before the latest changes and running against that branch.

    ![image](https://user-images.githubusercontent.com/89028299/145257604-e4caa1cb-f132-4c93-99be-39f38334e253.png)

**Comment by unaihuete93** [comment]
We probably need to disable tests temporarily. @rob-foulkrod please open an issue referencing this one (or the fix you found) on repository: https://github.com/microsoft/AzureDevOpsDemoGenerator/issues

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue
