### ISSUE TITLE
M09-LAB19: Teams does not support team creation

### ISSUE THREAD

**Issue by az400raf** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#321]
### Contact Details

az400raf@outlook.com

### What happened?

Exercise : 19
Task: 02
Step: 04

Description of issue:
The description says "install teams using defaults". It is  hard to say what is the default, when you are asked "how are you going to use teams"? The installation finished with a private teams with no option to create a team. Please direct, how to configure teams. I don't have a ms 365 subscription, it should be granted at least as a try for the course duration time. If I need to request it somehow, please describe how to do it.
I also don't know how to correct the steps (if I by mistake do something incorrectly)

Repro steps:
1. Follow manual (and use default options)

### Lab

Lab 19 Integration between Azure DevOps and Microsoft Teams

### Relevant screenshots

![image](https://user-images.githubusercontent.com/118273632/202398712-3c5bc156-7d4d-4b04-b80f-4e8432782e50.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
@petender @LuizMacedo we should delete this lab, many learners do not have the right to create a Team and do the lab.

**Comment by unaihuete93** [comment]
#378

**Comment by petender** [comment]
I have a demo I do with Slack integration... should we consider rewriting this lab with Slack instead of Teams? They just need to create a Slack account and use all from the browser...

Give it a thought, happy to work on that...

Thx, P

***@***.***
Peter De Tender
Microsoft Technical Trainer
M:425 691 6411
***@***.******@***.***>      | @pdtit<https://twitter.com/pdtit>     | https://aka.ms/pdtit
Learn.Microsoft.com<https://Learn.Microsoft.com>
Microsoft Learn. Spark possibility.

**Comment by LuizMacedo** [comment]
Closing this issue since the lab is now deprecated by #422. Thanks!
