### ISSUE TITLE
LAB15: .NET Version, Visual Studio Options, and Pack Instructions

### ISSUE THREAD

**Issue by dmbogdan001** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#500]
### Contact Details

dmbogdan001@gmail.com

### What should we change?

Step 4 - Visual Studio 2019 didn't give a version option 
Step 16 - .\nuget pack didn't work with 6.7.x (latest version as recommended by lab), so ran dotnet pack instead
Step 17 - as a result of above, location of EShopOnWeb.Shared.1.0.0.nupkg is now located in /bin/debug subdirectory

### Lab

Lab 15 Package management with Azure Artifacts

### Relevant screenshots

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/79425434/03ebd847-d5cf-43bc-b0d5-8690b76518a3)

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/79425434/22b7e908-07e6-459d-9a50-93e2185ce6e2)

**Comment by petender** [comment]
Dear, thank you for raising the issue. Since you mention Visual Studio 2019, it is important to know that version doesn't officially support .NET6 framework (see this thread for more details: https://github.com/dotnet/core/issues/5567#issuecomment-1105996161)

Hence the instructions having Visual Studio 2022 as prerequisite. That's also the version we used for building and testing the lab. Wondering if you could try again using that latest version and let us know if you have similar issues. Kind regards, Peter
