### ISSUE TITLE
Markdown issue with Demo generator

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#55]
# Module: 01
#### Step: 1 On your lab computer, start a web browser and navigate to 

Description of issue

Please fix the markdown on LODS, it's difficult to navigate to the Demo generator. If you click on the link it will open a new window on the local computer. Not on the LODS VM.
Would be great to add the T at the left to open the address inside the VM. 

Repro steps:

1. On your lab computer, start a web browser and navigate to Azure DevOps Demo Generator. This utility site will automate the process of creating a new Azure DevOps project within your account that is prepopulated with content (work items, repos, etc.) required for the lab.

**Comment by TesterTesterson1004** [comment]
Hi, I was just checking LODS site for this issue and they appear to have updated it.  However, I should also note that since this repo can be implemented by various lab hosters and is focused on course-wide errors/issues, if you have a problem that may be specific to one particular lab hoster (such as LODS) you'll want to post that through their Support channels rather then directly against this repo.

**Comment by mkennten** [comment]
Looks like this issue has been addressed in the current verion.
