### ISSUE TITLE
M01-Agile planning and portfolio management with Azure Boards: UI discrepancies

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#573]
### Contact Details

steve@wigf1.net

### What happened?

Description of issue:

Numerous images in the lab have legacy UI screenshots, some later images show what students will see. Earlier screenshots confuse students.

I modified some images, with appropriate blurs per the originals. 
I also changed button captions where they had also changed.

### Lab

Agile planning and portfolio management with Azure Boards

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [X] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Thanks, @WigF1 for this PR. I appreciate your help!

Suggestion: next time I suggest splitting in small PRs so we can review and validate in all our environments and partners faster. I was busy with other issues, so that also impacted the approval and validation. 

Thanks @yashints and @rob-foulkrod!
